version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: beckend
    volumes:
      - static-data:/code/collected_static
    command: shell
    environment:
      - DEBUG=False
      - APP_LOGGING_LEVEL=${APP_LOGGING_LEVEL}
      - DB_LOGGING_LEVEL=${DB_LOGGING_LEVEL}
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      main:
        aliases:
          - backend
  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - postgres14-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_HOSTNAME}
    ports:
      - 5432:5432
    networks:
      main:
        aliases:
          - postgres

volumes:
  postgres14-data: {}
  static-data: {}

networks:
  main: