version: "3.7"

services:
  nginx:
    build:
        context: .
        dockerfile: src/nginx/Dockerfile
    container_name: nginx
    volumes:
      - static-data:/code/collected_static
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      main:
        aliases:
          - nginx
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: beckend
    volumes:
      - static-data:/code/collected_static
    command: runserver
    environment:
      - DEBUG=False
      - APP_LOGGING_LEVEL=${APP_LOGGING_LEVEL}
      - DB_LOGGING_LEVEL=${DB_LOGGING_LEVEL}
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
    expose:
      - 8000
    depends_on:
      - postgres
    networks:
      main:
        aliases:
          - backend
  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - postgres14-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      main:
        aliases:
          - postgres

volumes:
  postgres14-data: {}
  static-data: {}

networks:
  main: