# Generated by Django 3.2.8 on 2021-12-09 06:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("total_price", models.IntegerField(null=True)),
                (
                    "external_client",
                    models.CharField(
                        max_length=128,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="This parameter does not comply with allowed characters.",
                                regex="^[A-Z a-z Ñ ñ . ' _]+$",
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=None, null=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
