# Generated by Django 3.2.8 on 2021-12-09 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_productquantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productquantity",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_quantities",
                to="api.order",
            ),
        ),
    ]
